/* @flow */
window.gcexports.globalLexicon = {
  "precision" : { "tk": 1, "name": "PRECISION", "cls": "function", "length": 2 , "arity": 2 },
  "variable" : { "tk": 1, "name": "VARIABLE", "cls": "function", "length": 2 , "arity": 2 },
  "domain" : { "tk": 1, "name": "DOMAIN", "cls": "function", "length": 2 , "arity": 2 },
  "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
  "pow" : { "tk": 1, "name": "POW", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "calculate" : { "tk": 1, "name": "CALCULATE", "cls": "function", "length": 1 , "arity": 1 },
  "solve" : { "tk": 1, "name": "SOLVE", "cls": "function", "length": 1 , "arity": 1 },
  "simplify" : { "tk": 1, "name": "SIMPLIFY", "cls": "function", "length": 1 , "arity": 1 },
  "expand" : { "tk": 1, "name": "EXPAND", "cls": "function", "length": 1 , "arity": 1 },
  "factor" : { "tk": 1, "name": "FACTOR", "cls": "function", "length": 1 , "arity": 1 },
  "eval" : { "tk": 1, "name": "EVAL", "cls": "function", "length": 1 , "arity": 1 },
  "match" : { "tk": 1, "name": "MATCH", "cls": "function", "length": 2 , "arity": 2 },
  "apart" : { "tk": 1, "name": "APART", "cls": "function", "length": 1 , "arity": 1 },
  "cancel" : { "tk": 1, "name": "CANCEL", "cls": "function", "length": 1 , "arity": 1 },
  "collect" : { "tk": 1, "name": "COLLECT", "cls": "function", "length": 1 , "arity": 1 },
  "integrate" : { "tk": 1, "name": "INTEGRATE", "cls": "function", "length": 1 , "arity": 1 },
  "diff" : { "tk": 1, "name": "DIFF", "cls": "function", "length": 1 , "arity": 1 },
  "decimal" : { "tk": 1, "name": "DECIMAL", "cls": "function", "length": 1 , "arity": 1 },
  "literal" : { "tk": 1, "name": "LITERAL", "cls": "function", "length": 1 , "arity": 1 },
  "seed" : { "tk": 1, "name": "LITERAL", "cls": "function", "length": 1 , "arity": 1 },
  "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
  "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
  "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
  "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
  "apply" : { "tk": 1, "name": "APPLY", "cls": "function", "length": 2, "arity": 2 },
  "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 0, "arity": 0 },
  "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 }
}
