/* @flow */
// The lexicon must be the last definition and the only one with a left curly.
window.gcexports.globalLexicon = {
  "precision" : { "tk": 1, "name": "PRECISION", "cls": "function", "length": 2 , "arity": 2 },
  "variable" : { "tk": 1, "name": "VARIABLE", "cls": "function", "length": 2 , "arity": 2 },
  "domain" : { "tk": 1, "name": "DOMAIN", "cls": "function", "length": 2 , "arity": 2 },
  "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 1 , "arity": 1 },
  "and" : { "tk": 1, "name": "AND", "cls": "function", "length": 1 , "arity": 1 },
  "or" : { "tk": 1, "name": "OR", "cls": "function", "length": 1 , "arity": 1 },
  "add" : { "tk": 1, "name": "ADD", "cls": "function", "length": 2 , "arity": 2 },
  "sub" : { "tk": 1, "name": "SUB", "cls": "function", "length": 2 , "arity": 2 },
  "mul" : { "tk": 1, "name": "MUL", "cls": "function", "length": 2 , "arity": 2 },
  "div" : { "tk": 1, "name": "DIV", "cls": "function", "length": 2 , "arity": 2 },
  "pow" : { "tk": 1, "name": "POW", "cls": "function", "length": 2 , "arity": 2 },
  "style" : { "tk": 1, "name": "STYLE", "cls": "function", "length": 2, "arity": 2 },
  "rubric" : { "tk": 1, "name": "RUBRIC", "cls": "function", "length": 2, "arity": 2 },
  "calculate" : { "tk": 1, "name": "CALCULATE", "cls": "function", "length": 1 , "arity": 1 },
  "solve" : { "tk": 1, "name": "SOLVE", "cls": "function", "length": 1 , "arity": 1 },
  "simplified" : { "tk": 1, "name": "SIMPLIFIED", "cls": "function", "length": 0, "arity": 0 },
  "expanded" : { "tk": 1, "name": "EXPANDED", "cls": "function", "length": 0 , "arity": 0 },
  "factored" : { "tk": 1, "name": "FACTORED", "cls": "function", "length": 0 , "arity": 0 },
  "sympy" : { "tk": 1, "name": "SYMPY", "cls": "function", "length": 1 , "arity": 1 },
  "symbolic" : { "tk": 1, "name": "SYMBOLIC", "cls": "function", "length": 1 , "arity": 1 },
  "syntax" : { "tk": 1, "name": "SYNTAX", "cls": "function", "length": 1 , "arity": 1 },
  "istrue" : { "tk": 1, "name": "IS-TRUE", "cls": "function", "length": 0 , "arity": 0 },
  "isvalid" : { "tk": 1, "name": "IS-VALID", "cls": "function", "length": 0 , "arity": 0 },
  "isunit" : { "tk": 1, "name": "IS-UNIT", "cls": "function", "length": 1 , "arity": 1 },
  "simplify" : { "tk": 1, "name": "SIMPLIFY", "cls": "function", "length": 1 , "arity": 1 },
  "trigsimp" : { "tk": 1, "name": "TRIGSIMP", "cls": "function", "length": 1 , "arity": 1 },
  "expand" : { "tk": 1, "name": "EXPAND", "cls": "function", "length": 1 , "arity": 1 },
  "factor" : { "tk": 1, "name": "FACTOR", "cls": "function", "length": 1 , "arity": 1 },
  "eval" : { "tk": 1, "name": "EVAL", "cls": "function", "length": 1 , "arity": 1 },
  "match" : { "tk": 1, "name": "MATCH", "cls": "function", "length": 2 , "arity": 2 },
  "apart" : { "tk": 1, "name": "APART", "cls": "function", "length": 1 , "arity": 1 },
  "cancel" : { "tk": 1, "name": "CANCEL", "cls": "function", "length": 1 , "arity": 1 },
  "collect" : { "tk": 1, "name": "COLLECT", "cls": "function", "length": 1 , "arity": 1 },
  "integrate" : { "tk": 1, "name": "INTEGRATE", "cls": "function", "length": 1 , "arity": 1 },
  "diff" : { "tk": 1, "name": "DIFF", "cls": "function", "length": 1 , "arity": 1 },
  "decimal" : { "tk": 1, "name": "DECIMAL", "cls": "function", "length": 1 , "arity": 1 },
  "literal" : { "tk": 1, "name": "LITERAL", "cls": "function", "length": 1, "arity": 1 },
  "ignoreOrder" : { "tk": 1, "name": "IGNORE-ORDER", "cls": "function", "length": 1, "arity": 1 },
  "inverseResult" : { "tk": 1, "name": "INVERSE-RESULT", "cls": "function", "length": 1 , "arity": 1 },
  "not" : { "tk": 1, "name": "INVERSE-RESULT", "cls": "function", "length": 1 , "arity": 1 },

  "field" : { "tk": 1, "name": "FIELD", "cls": "function", "length": 2, "arity": 2 },
  "decimalPlaces" : { "tk": 1, "name": "DECIMAL-PLACES", "cls": "function", "length": 2, "arity": 2 },
  "setThousandsSeparator" : { "tk": 1, "name": "SET-THOUSANDS-SEPARATOR", "cls": "function", "length": 2, "arity": 2 },
  "setDecimalSeparator" : { "tk": 1, "name": "SET-DECIMAL-SEPARATOR", "cls": "function", "length": 2, "arity": 2 },


  "allowDecimal" : { "tk": 1, "name": "ALLOW-DECIMAL", "cls": "function", "length": 1 , "arity": 1 },
  "allowInterval" : { "tk": 1, "name": "ALLOW-INTERVAL", "cls": "function", "length": 1 , "arity": 1 },
  "allowThousandsSeparator" : { "tk": 1, "name": "ALLOW-THOUSANDS-SEPARATOR", "cls": "function", "length": 1 , "arity": 1 },
  "compareSides" : { "tk": 1, "name": "COMPARE-SIDES", "cls": "function", "length": 1 , "arity": 1 },
  "compareGrouping" : { "tk": 1, "name": "COMPARE-GROUPING", "cls": "function", "length": 1 , "arity": 1 },
  "ignoreText" : { "tk": 1, "name": "IGNORE-TEXT", "cls": "function", "length": 1 , "arity": 1 },
  "ignoreTrailingZeros" : { "tk": 1, "name": "IGNORE-TRAILING-ZEROS", "cls": "function", "length": 1 , "arity": 1 },
  "ignoreCoefficientOne" : { "tk": 1, "name": "IGNORE-COEFFICIENT-ONE", "cls": "function", "length": 1 , "arity": 1 },
  "allowEulersNumber" : { "tk": 1, "name": "ALLOW-EULERS-NUMBER", "cls": "function", "length": 1 , "arity": 1 },



  "seed" : { "tk": 1, "name": "SEED", "cls": "function", "length": 1 , "arity": 1 },
  "stimulus" : { "tk": 1, "name": "STIMULUS", "cls": "function", "length": 1 , "arity": 1 },
  "solution" : { "tk": 1, "name": "SOLUTION", "cls": "function", "length": 1 , "arity": 1 },
  "format" : { "tk": 1, "name": "FORMAT", "cls": "function", "length": 2 , "arity": 2 },
  "choices" : { "tk": 1, "name": "CHOICES", "cls": "function", "length": 1 , "arity": 1 },
  "val" : { "tk": 1, "name": "VAL", "cls": "function", "length": 2 , "arity": 2 },
  "key" : { "tk": 1, "name": "KEY", "cls": "function", "length": 2 , "arity": 2 },
  "len" : { "tk": 1, "name": "LEN", "cls": "function", "length": 1 , "arity": 1 },
  "map" : { "tk": 1, "name": "MAP", "cls": "function", "length": 2, "arity": 2 },
  "apply" : { "tk": 1, "name": "APPLY", "cls": "function", "length": 2, "arity": 2 },
  "in" : { "tk": 1, "name": "IN", "cls": "function", "length": 1, "arity": 1 },
  "arg" : { "tk": 1, "name": "ARG", "cls": "function", "length": 1, "arity": 1 },
  "gen" : { "tk": 1, "name": "FORMULA", "cls": "function", "length": 1 , "arity": 1 },
  "desmos" : { "tk": 1, "name": "DESMOS", "cls": "function", "length": 2 , "arity": 2 },
  "slope-intercept" : { "tk": 1, "cls": "string", "val": "desmos_slope_intercept_question", "length": 0, "arity": 0 },
  "sqrt" : { "tk": 1, "cls": "string", "val": "desmos_sqrt_question", "length": 0, "arity": 0 },
  "parabola" : { "tk": 1, "cls": "string", "val": "desmos_parabola_question", "length": 0, "arity": 0 },
  "circle" : { "tk": 1, "cls": "string", "val": "desmos_circle_question", "length": 0, "arity": 1  },
  "rectangle" : { "tk": 1, "cls": "string", "val": "desmos_rectangle_question", "length": 0, "arity": 0 },
  "volume" : { "tk": 1, "cls": "string", "val": "desmos_volume_question", "length": 0, "arity": 0 },
  "formula" : { "tk": 1, "name": "FORMULA", "cls": "function", "length": 1 , "arity": 1 },
  "formula-essay" : { "tk": 1, "name": "FORMULA-ESSAY", "cls": "function", "length": 1 , "arity": 1 },
  "mcq" : { "tk": 1, "name": "MCQ", "cls": "function", "length": 1 , "arity": 1 },
  "latex" : { "tk": 1, "name": "LATEX", "cls": "function", "length": 1 , "arity": 1 },
  "title" : { "tk": 1, "name": "TITLE", "cls": "function", "length": 2 , "arity": 2 },
  "numeric" : { "tk": 1, "name": "NUMERIC", "cls": "function", "length": 1 , "arity": 1 },
  "value" : { "tk": 1, "name": "NUMERIC", "cls": "function", "length": 1 , "arity": 1 },
  "context" : { "tk": 1, "name": "CONTEXT", "cls": "function", "length": 2 , "arity": 2 },
  "template" : { "tk": 1, "name": "TEMPLATE", "cls": "function", "length": 2 , "arity": 2 },
  "notes" : { "tk": 1, "name": "NOTES", "cls": "function", "length": 2 , "arity": 2 },
  "index" : { "tk": 1, "name": "INDEX", "cls": "function", "length": 2 , "arity": 2 },
  "result" : { "tk": 1, "name": "RESULT", "cls": "function", "length": 0 , "arity": 0 },
  "params" : { "tk": 1, "name": "PARAMS", "cls": "function", "length": 1 , "arity": 1 }
}
